# Generated by Django 5.1.2 on 2024-12-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_channel_users_remove_role_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
