# Generated by Django 5.1.2 on 2025-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_events_members_events_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics"
            ),
        ),
    ]
