# Generated by Django 5.1.2 on 2025-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_events_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images"),
        ),
    ]
