# Generated by Django 5.1.2 on 2025-01-03 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_events_event_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="invitepending",
            field=models.ManyToManyField(
                related_name="pending", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
