# Generated by Django 5.1.2 on 2025-01-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_role_event_alter_role_members_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_edit_event',
            field=models.BooleanField(default=False),
        ),
    ]
