# Generated by Django 5.1.2 on 2025-01-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_role_can_edit_event'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_delete_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='event_roles', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events'),
        ),
    ]
