# Generated by Django 5.1.2 on 2025-01-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_message_channel_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.events'),
        ),
    ]
